options:
  mirror_list:
    type: string
    default: "[{url: 'http://cloud-images.ubuntu.com/releases/',
                name_prefix: 'ubuntu:released',
                path: 'streams/v1/index.sjson', max: 1,
                item_filters: ['release=trusty', 'arch~(x86_64|amd64)', 'ftype~(disk1.img|disk.img)']}]"
    description: >
      YAML-formatted list of simplestreams mirrors and their configuration
      properties. Defaults to downloading the released images from
      cloud-images.ubuntu.com.
  run:
    type: boolean
    default: True
    description: "Should the sync be running or not?"
  use_swift:
    type: boolean
    default: True
    description: "Should the charm set up the product-streams endpoint with swift's URLs?"
  frequency:
    type: string
    default: "daily"
    description: "cron job frequency - one of ['hourly', 'daily', 'weekly']"
  region:
    type: string
    default: "RegionOne"
    description: "Openstack region to operate in."
  cloud_name:
    type: string
    default: "glance-simplestreams-sync-openstack"
    description: "Cloud name to be used in simplestreams index file"
  name_prefix:
    type: string
    default: "auto-sync/"
    description: "This is prefixed to the object name when uploading to glance."
