options:
  mirror_list:
    type: string
    default: "[{url: 'http://cloud-images.ubuntu.com/releases/',
                name_prefix: 'ubuntu:released',
                path: 'streams/v1/index.sjson', max: 1,
                item_filters: ['release=trusty', 'arch~(x86_64|amd64)', 'ftype~(disk1.img|disk.img)']}]"
    description: >
      YAML-formatted list of simplestreams mirrors and their configuration
      properties. Defaults to downloading the released images from
      cloud-images.ubuntu.com.
  run:
    type: boolean
    default: True
    description: "Should the sync be running or not?"
  use_swift:
    type: boolean
    default: True
    description: "Should the charm set up the product-streams endpoint with swift's URLs?"
  frequency:
    type: string
    default: "daily"
    description: "cron job frequency - one of ['hourly', 'daily', 'weekly']"
  region:
    type: string
    default: "RegionOne"
    description: "Openstack region to operate in."
  cloud_name:
    type: string
    default: "glance-simplestreams-sync-openstack"
    description: "Cloud name to be used in simplestreams index file"
  name_prefix:
    type: string
    default: "auto-sync/"
    description: "This is prefixed to the object name when uploading to glance."
  content_id_template:
    type: string
    default: "auto.sync"
    description: >
      A Python-style .format() template to use when generating
      content_id properties for images uploaded to glance.

      The content_id is considered when matching images between the
      source and destination to decide which images to mirror.  By
      varying this value you can mirror disjoint sets of images from
      the same source into a single glance, either by using multiple
      deployments of this charm, or by using a tool such as
      sstream-mirror-glance, and they will not interfere with each
      other.

      Here is a more interesting example value:

          com.example.customstack.{region}:ubuntu:celery-worker

      Currently the only available substitution is "region".  Any
      other attempted substitutions will break the sync script.
  rabbit-user:
    default: glance-simplestreams-sync
    type: string
    description: Username to request access on rabbitmq-server.
  rabbit-vhost:
    default: openstack
    type: string
    description: RabbitMQ virtual host to request access on rabbitmq-server.
