options:
  mirror_list:
    type: string
    default: "[{url: 'http://cloud-images.ubuntu.com/releases/',
                name_prefix: 'ubuntu:released',
                path: 'streams/v1/index.sjson', max: 1}]"
    description: >
      YAML-formatted list of simplestreams mirrors and their configuration
      properties. Defaults to downloading the released images from
      cloud-images.ubuntu.com.
  run:
    type: boolean
    default: True
    description: "Should the sync be running or not?"
  use_swift:
    type: boolean
    default: True
    description: "Should the charm set up the product-streams endpoint with swift's URLs?"
  frequency:
    type: string
    default: "daily"
    description: "cron job frequency - one of ['hourly', 'daily', 'weekly']"
  region:
    type: string
    default: "RegionOne"
    description: "Openstack region to operate in."
