options:
  url:
    type: string
    default: "http://cloud-images.ubuntu.com/releases/"
    description: "Mirror base URL"
  name_prefix:
    type: string
    default: "com.ubuntu.cloud:released:download"
    description: "Image type identifier string"
  path:
    type: string
    default: "streams/v1/index.sjson"
    description: "Path to SimpleStream JSON index file"
  max:
    type: int
    default: 1
    description: "Max number of images to keep in glance"
  run:
    type: boolean
    default: False
    description: "Should the sync be running or not?"
